# Directions, Rotations, and Hyperspheres

# 方向，旋转，和超球面

Directional statistics involve data and/or parameters that are constrained to be directions. The set of directions forms a sphere, the geometry of which is not smoothly mappable to that of a Euclidean space because you can move around a sphere and come back to where you started.

方向统计涉及数据和（或）参数被约束为方向。 这组方向形成一个球体，其几何形状不能平滑地映射到欧几里得空间因为你可以围绕一个球体移动并返回到你开始的地方。

This is why it is impossible to make a map of the globe on a flat piece of paper where all points that are close to each other on the globe are close to each other on the flat map. The fundamental problem is easy to visualize in two dimensions, because as you move around a circle, you wind up back where you started. In other words, 0 degrees and 360 degrees (equivalently, 0 and $2 \pi$ radians) pick out the same point, and the distance between 359 degrees and 2 degrees is the same as the distance between 137 and 140 degrees.

这就是为什么不可能在平面上绘制球体地图的原因当球体上所有彼此接近的点都在平面地图上彼此靠近。 这个根本问题很容易解决在二维空间中可视化，因为当你绕圈移动时，你回到你开始的地方。 换句话说，0 度和 360度（相当于 0 和 $2 \pi$ ）选取相同的点， 359 度和 2 度之间的距离与在 137 度和 140 度之间的距离相等。

Stan supports directional statistics by providing a unit-vector data type, the values of which determine points on a hypersphere (circle in two dimensions, sphere in three dimensions).

Stan 通过提供单位向量数据类型来支持方向统计，其值确定超球面（二维中的圆，三维中的球体）上的点。

## Unit vectors

## 单位向量

The length of a vector $x \in \mathbb{R}^K$ is given by

向量 $x \in \mathbb{R}^K$ 的长度由下式给出

$$
\Vert x \Vert
= \sqrt{x^{\top}\,x}
= \sqrt{x_1^2 + x_2^2 + \cdots + x_K^2}.
$$

Unit vectors are defined to be vectors of unit length (i.e., length one).

单位向量被定义为单位长度（即长度为一）的向量。

With a variable declaration such as

使用变量声明，例如

``` stan
unit_vector[K] x;
```

the value of `x` will be constrained to be a vector of size `K` with unit length; the reference manual chapter on constrained parameter transforms provides precise definitions.

"x"的值将被限制为单位长度的大小为"K"的向量； 参考手册中关于约束参数变换的章节提供了精确的定义。

*Warning:* An extra term gets added to the log density to ensure the distribution on unit vectors is proper. This is not a problem in practice, but it may lead to misunderstandings of the target log density output (`lp__` in some interfaces). The underlying source of the problem is that a unit vector of size $K$ has only $K - 1$ degrees of freedom. But there is no way to map those $K - 1$ degrees of freedom continuously to $\mathbb{R}^N$---for example, the circle can't be mapped continuously to a line so the limits work out, nor can a sphere be mapped to a plane. A workaround is needed instead. Stan's unit vector transform uses $K$ unconstrained variables, then projects down to the unit hypersphere. Even though the hypersphere is compact, the result would be an improper distribution. To ensure the unit vector distribution is proper, each unconstrained variable is given a "Jacobian" adjustment equal to an independent standard normal distribution. Effectively, each dimension is drawn standard normal, then they are together projected down to the hypersphere to produce a unit vector. The result is a proper uniform distribution over the hypersphere.

警告：对数密度添加了一个额外项，以确保单位向量的分布正确。 这在实践中不是问题，但可能会导致对目标日志密度输出（某些接口中的"lp\_\_"）的误解。 问题的根本原因是大小为 $K$ 的单位向量只有 $K - 1$ 个自由度。 但是没有办法将这些 $K - 1$ 自由度连续映射到 $\mathbb{R}^N$，例如，圆不能连续映射到直线，因此限制成立， 球体也不能映射到平面。 相反，需要一种解决方法。 Stan 的单位向量变换使用 $K$ 无约束变量，然后向下投影到单位超球面。 即使超球面是紧凑的，结果也将是不正确的分布。 为了确保单位向量分布正确，每个无约束变量都被给予等于独立标准正态分布的"雅可比"调整。 实际上，每个维度都绘制标准法线，然后将它们一起投影到超球面以产生单位向量。 结果是超球面上的适当均匀分布。

```{r}

```

## Circles, spheres, and hyperspheres

## 圆、球体和超球体

An $n$-sphere, written $S^{n}$, is defined as the set of $(n + 1)$-dimensional unit vectors,

一个$n$ 球体，写作 $S^{n}$，定义为 $(n + 1)$ 维单位向量的集合，

$$
S^{n} = \left\{ x \in \mathbb{R}^{n+1} \: : \: \Vert x \Vert = 1 \right\}.
$$

Even though $S^n$ is made up of points in $(n+1)$ dimensions, it is only an $n$-dimensional manifold. For example, $S^2$ is defined as a set of points in $\mathbb{R}^3$, but each such point may be described uniquely by a latitude and longitude. Geometrically, the surface defined by $S^2$ in $\mathbb{R}^3$ behaves locally like a plane, i.e., $\mathbb{R}^2$. However, the overall shape of $S^2$ is not like a plane in that it is compact (i.e., there is a maximum distance between points). If you set off around the globe in a "straight line" (i.e., a geodesic), you wind up back where you started eventually; that is why the geodesics on the sphere ($S^2$) are called "great circles," and why we need to use some clever representations to do circular or spherical statistics.

尽管 $S^n$ 由 $(n+1)$ 维的点组成，但它只是一个 $n$ 维流形。 例如，$S^2$ 被定义为 $\mathbb{R}^3$ 中的一组点，但每个这样的点可以通过纬度和经度唯一地描述。 从几何角度来说，$\mathbb{R}^3$ 中的 $S^2$ 定义的表面在局部表现得像一个平面，即 $\mathbb{R}^2$。 然而，$S^2$ 的整体形状并不像平面那样紧凑（即点之间存在最大距离）。 如果你以"直线"（即测地线）绕地球一周，你最终会回到起点； 这就是为什么球体上的测地线 ($S^2$) 被称为"大圆"，也是为什么我们需要使用一些巧妙的表示来进行圆形或球形统计。

Even though $S^{n-1}$ behaves locally like $\mathbb{R}^{n-1}$, there is no way to smoothly map between them. For example, because latitude and longitude work on a modular basis (wrapping at $2\pi$ radians in natural units), they do not produce a smooth map.

尽管 $S^{n-1}$ 的本地行为类似于 $\mathbb{R}^{n-1}$，但无法在它们之间平滑映射。 例如，由于纬度和经度以模块化方式工作（以自然单位的 $2\pi$ 弧度包裹），因此它们不会生成平滑的地图。

Like a bounded interval $(a, b)$, in geometric terms, a sphere is compact in that the distance between any two points is bounded.

就像有界区间 $(a, b)$ 一样，在几何术语中，球体是紧致的，因为任何两点之间的距离都是有界的。

## Transforming to unconstrained parameters

## 转换为无约束参数

Stan (inverse) transforms arbitrary points in $\mathbb{R}^{K+1}$ to points in $S^K$ using the auxiliary variable approach of @Muller:1959. A point $y \in \mathbb{R}^K$ is transformed to a point $x \in S^{K-1}$ by

Stan（逆）使用 @Muller:1959 的辅助变量方法将 $\mathbb{R}^{K+1}$ 中的任意点转换为 $S^K$ 中的点。 点 $y \in \mathbb{R}^K$ 通过以下方式变换为点 $x \in S^{K-1}$

$$
x = \frac{y}{\sqrt{y^{\top} y}}.
$$

The problem with this mapping is that it's many to one; any point lying on a vector out of the origin is projected to the same point on the surface of the sphere. @Muller:1959 introduced an auxiliary variable interpretation of this mapping that provides the desired properties of uniformity; the reference manual contains the precise definitions used in the chapter on constrained parameter transforms.

这种映射的问题在于它是多对一的； 位于原点向量上的任何点都会投影到球体表面上的同一点。 @Muller：1959 年引入了此映射的辅助变量解释，它提供了所需的均匀性属性； 参考手册包含约束参数变换章节中使用的精确定义。

#### Warning: undefined at zero! {.unnumbered}

### 警告：未定义为零！ {.未编号}

The above mapping from $\mathbb{R}^n$ to $S^n$ is not defined at zero. While this point outcome has measure zero during sampling, and may thus be ignored, it is the default initialization point and thus unit vector parameters cannot be initialized at zero. A simple workaround is to initialize from a small interval around zero, which is an option built into all of the Stan interfaces.

上述从 $\mathbb{R}^n$ 到 $S^n$ 的映射未定义为零。 虽然该点结果在采样期间测量为零，因此可以被忽略，但它是默认初始化点，因此单位向量参数不能初始化为零。 一个简单的解决方法是从零附近的小间隔进行初始化，这是所有 Stan 接口中内置的一个选项。

## Unit vectors and rotations

## 单位向量和旋转

Unit vectors correspond directly to angles and thus to rotations. This is easy to see in two dimensions, where a point on a circle determines a compass direction, or equivalently, an angle $\theta$. Given an angle $\theta$, a matrix can be defined, the pre-multiplication by which rotates a point by an angle of $\theta$. For angle $\theta$ (in two dimensions), the $2 \times 2$ rotation matrix is defined by

单位向量直接对应于角度，从而对应于旋转。 这在二维中很容易看出，其中圆上的点确定罗盘方向，或者等效地，角度 $\theta$。 给定角度$\theta$，可以定义一个矩阵，预乘将点旋转$\theta$角度。 对于角度 $\theta$（二维），$2 \times 2$ 旋转矩阵定义为

$$
R_{\theta}
=
\begin{bmatrix}
\cos \theta & -\sin \theta \\
\sin \theta &  \cos \theta
\end{bmatrix}.
$$ Given a two-dimensional vector $x$, $R_{\theta} \, x$ is the rotation of $x$ (around the origin) by $\theta$ degrees.

给定一个二维向量$x$，$R_{\theta}\，x$是$x$（绕原点）旋转$\theta$度。

### Angles from unit vectors {.unnumbered}

### 单位向量的角度（未编号）

Angles can be calculated from unit vectors. For example, a random variable `theta` representing an angle in $(-\pi, \pi)$ radians can be declared as a two-dimensional unit vector then transformed to an angle.

角度可以根据单位向量计算。 例如，表示以 $(-\pi, \pi)$ 弧度表示的角度的随机变量"theta"可以声明为二维单位向量，然后转换为角度。

``` stan
parameters {
  unit_vector[2] xy;
}
transformed parameters {
  real<lower=-pi(), upper=pi()> theta = atan2(xy[2], xy[1]);
}
```

If the distribution of $(x, y)$ is uniform over a circle, then the distribution of $\arctan \frac{y}{x}$ is uniform over $(-\pi, \pi)$.

如果 $(x, y)$ 在圆上分布均匀，则 $\arctan \frac{y}{x}$ 在 $(-\pi, \pi)$ 上均匀分布。

It might be tempting to try to just declare `theta` directly as a parameter with the lower and upper bound constraint as given above. The drawback to this approach is that the values $-\pi$ and $\pi$ are at $-\infty$ and $\infty$ on the unconstrained scale, which can produce multimodal posterior distributions when the true distribution on the circle is unimodal.

尝试直接将"theta"声明为具有上面给出的下限和上限约束的参数可能很诱人。 这种方法的缺点是，值 $-\pi$ 和 $\pi$ 在无约束尺度上位于 $-\infty$ 和 $\infty$ 处，当圆上的真实分布为 单峰。

With a little additional work on the trigonometric front, the same conversion back to angles may be accomplished in more dimensions.

通过在三角学方面进行一些额外的工作，可以在更多维度上完成同样的转换回角度。

## Circular representations of days and years

## 日期和年份的循环表示

A 24-hour clock naturally represents the progression of time through the day, moving from midnight to noon and back again in one rotation. A point on a circle divided into 24 hours is thus a natural representation for the time of day. Similarly, years cycle through the seasons and return to the season from which they started.

24 小时时钟自然地代表了一天中的时间进程，从午夜移动到中午，然后再返回一次。 因此，划分为 24 小时的圆上的一点是一天中时间的自然表示。 同样，岁月在季节中循环，又回到它们开始的季节。

In human affairs, temporal effects often arise by convention. These can be modeled directly with ad-hoc predictors for holidays and weekends, or with data normalization back to natural scales for daylight savings time.

在人类事务中，时间效应常常按照惯例出现。 这些可以直接使用假期和周末的临时预测器进行建模，或者将数据标准化回夏令时的自然比例。